const catalogue = [
  {
    id: 1,
    name: "Rose Bouquet",
    category: "Bouquets",
    type: "product",
    description:
      "A classic arrangement of fresh red roses, perfect for any occasion.",
    priceLabel: "KSH 1,500",
    image: "https://images.unsplash.com/photo-1487530811015-780780169993?w=600",
    badge: "Popular",
    specs: ["12 stems", "Fresh cut", "Gift wrapped"],
  },
  {
    id: 2,
    name: "Mixed Wildflowers",
    category: "Bouquets",
    type: "product",
    description: "A vibrant mix of seasonal wildflowers bursting with colour.",
    priceLabel: "KSH 1,200",
    image: "https://images.unsplash.com/photo-1490750967868-88df5691cc8f?w=600",
    specs: ["Seasonal flowers", "Gift wrapped"],
  },
  {
    id: 3,
    name: "Sunflower Bundle",
    category: "Bouquets",
    type: "product",
    description: "Bright and cheerful sunflowers to light up any room.",
    priceLabel: "KSH 1,000",
    image: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=600",
    specs: ["6 stems", "Gift wrapped"],
  },
  {
    id: 4,
    name: "Wedding Decoration",
    category: "Events",
    type: "service",
    description:
      "Full floral decoration for your wedding venue — arches, tables, and more.",
    priceLabel: "From KSH 25,000",
    image: "https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=600",
    badge: "Premium",
    includes: [
      "Venue consultation",
      "Floral arch",
      "Table centerpieces",
      "Boutonnieres",
    ],
  },
  {
    id: 5,
    name: "Birthday Setup",
    category: "Events",
    type: "service",
    description:
      "Make their birthday unforgettable with a stunning floral setup.",
    priceLabel: "From KSH 8,000",
    image: "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=600",
    includes: ["Balloon & flower combo", "Table arrangement", "Delivery"],
  },
  {
    id: 6,
    name: "Corporate Event Decor",
    category: "Events",
    type: "service",
    description:
      "Elegant floral arrangements for conferences, launches and corporate events.",
    priceLabel: "From KSH 15,000",
    image: "https://images.unsplash.com/photo-1478146896981-b80fe463b330?w=600",
    includes: ["Reception flowers", "Stage decor", "Table centerpieces"],
  },
  {
    id: 7,
    name: "Tulip Bunch",
    category: "Seasonal",
    type: "product",
    description: "Fresh seasonal tulips in a variety of colours.",
    priceLabel: "KSH 900",
    image: "https://images.unsplash.com/photo-1520763185298-1b434c919102?w=600",
    badge: "New",
  },
  {
    id: 8,
    name: "Bridal Bouquet",
    category: "Wedding",
    type: "service",
    description: "Handcrafted bridal bouquet tailored to your wedding theme.",
    priceLabel: "From KSH 5,000",
    image: "https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=600",
    includes: ["Consultation", "Custom arrangement", "Delivery on wedding day"],
  },
];

export default catalogue;
